# Makefile for Lab Assignment 3
CC=gcc
CFLAGS=-Wall -Wextra -O2 -std=c11

all: task1 task2

task1: task1.c
	$(CC) $(CFLAGS) task1.c -o task1

task2: task2.c
	$(CC) $(CFLAGS) task2.c -o task2

clean:
	rm -f task1 task2
